# Generated by Django 4.2.29 on 2026-03-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('GENERAL', 'GENERAL'), ('EV', 'EV'), ('DISABLED', 'DISABLED')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'VEHICLE',
            },
        ),
    ]
