# Generated by Django 4.2.29 on 2026-03-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SagaOperation',
            fields=[
                ('operation_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('saga_type', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=32)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('current_step', models.CharField(blank=True, max_length=64, null=True)),
                ('failed_step', models.CharField(blank=True, max_length=64, null=True)),
                ('history_id', models.BigIntegerField(blank=True, null=True)),
                ('vehicle_num', models.CharField(blank=True, max_length=20, null=True)),
                ('slot_id', models.BigIntegerField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('last_error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('error_status', models.IntegerField(blank=True, null=True)),
                ('error_payload', models.JSONField(blank=True, null=True)),
                ('compensation_attempts', models.IntegerField(default=0)),
                ('completed_compensations', models.JSONField(blank=True, default=list)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'SAGA_OPERATION',
            },
        ),
        migrations.AddConstraint(
            model_name='sagaoperation',
            constraint=models.UniqueConstraint(fields=('saga_type', 'idempotency_key'), name='uniq_saga_operation_type_idempotency_key'),
        ),
    ]
