# Generated by Django 4.2.29 on 2026-03-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotType',
            fields=[
                ('slot_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'SLOT_TYPE',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ZONE',
            },
        ),
    ]
