# Generated by Django 4.2.29 on 2026-03-10 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zone_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ParkingSlot",
            fields=[
                ("slot_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slot_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parking_slots",
                        to="zone_service.slottype",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parking_slots",
                        to="zone_service.zone",
                    ),
                ),
            ],
            options={
                "db_table": "ZONE_PARKING_SLOT",
            },
        ),
    ]
