ENTRY_SAGA_TYPE = "ENTRY"
EXIT_SAGA_TYPE = "EXIT"

STATUS_COMPLETED = "COMPLETED"
STATUS_COMPENSATED = "COMPENSATED"
STATUS_FAILED = "FAILED"
STATUS_IN_PROGRESS = "IN_PROGRESS"

STEP_VALIDATE_VEHICLE = "VALIDATE_VEHICLE"
STEP_VALIDATE_ZONE_POLICY = "VALIDATE_ZONE_POLICY"
STEP_PARKING_COMMAND_ENTRY = "PARKING_COMMAND_ENTRY"
STEP_UPDATE_QUERY_ENTRY = "UPDATE_QUERY_ENTRY"

STEP_VALIDATE_ACTIVE_PARKING = "VALIDATE_ACTIVE_PARKING"
STEP_PARKING_COMMAND_EXIT = "PARKING_COMMAND_EXIT"
STEP_UPDATE_QUERY_EXIT = "UPDATE_QUERY_EXIT"

COMPENSATE_QUERY_ENTRY = "COMPENSATE_QUERY_ENTRY"
COMPENSATE_PARKING_ENTRY = "COMPENSATE_PARKING_ENTRY"
COMPENSATE_QUERY_EXIT = "COMPENSATE_QUERY_EXIT"
COMPENSATE_PARKING_EXIT = "COMPENSATE_PARKING_EXIT"
