# Generated by Django 4.2.29 on 2026-03-10 08:20

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentParkingView',
            fields=[
                ('vehicle_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('history_id', models.BigIntegerField(blank=True, null=True)),
                ('zone_id', models.BigIntegerField(blank=True, null=True)),
                ('slot_id', models.BigIntegerField(blank=True, null=True)),
                ('zone_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slot_name', models.CharField(blank=True, max_length=50, null=True)),
                ('slot_type', models.CharField(max_length=50)),
                ('entry_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'CURRENT_PARKING_VIEW',
            },
        ),
        migrations.CreateModel(
            name='ParkingQueryOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PARKING_QUERY_OPERATION',
            },
        ),
        migrations.CreateModel(
            name='ZoneAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.BigIntegerField()),
                ('slot_type', models.CharField(max_length=50)),
                ('total_count', models.IntegerField()),
                ('occupied_count', models.IntegerField()),
                ('available_count', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ZONE_AVAILABILITY',
                'indexes': [models.Index(fields=['zone_id', 'slot_type'], name='idx_zone_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='zoneavailability',
            constraint=models.UniqueConstraint(fields=('zone_id', 'slot_type'), name='uniq_zone_availability_zone_slot_type'),
        ),
        migrations.AddConstraint(
            model_name='zoneavailability',
            constraint=models.CheckConstraint(check=models.Q(('available_count', django.db.models.expressions.CombinedExpression(models.F('total_count'), '-', models.F('occupied_count'))), ('available_count__gte', 0)), name='chk_zone_availability_available_count'),
        ),
        migrations.AddConstraint(
            model_name='parkingqueryoperation',
            constraint=models.UniqueConstraint(fields=('operation_id', 'action'), name='uniq_parking_query_operation_action'),
        ),
    ]
