# Generated by Django 4.2.29 on 2026-03-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_query_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentparkingview",
            name="slot_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
